import { RecipeStore } from '../models/recipe-store';
import { ExtractedRecipe, RecipeExtractor } from '../services/recipe-extractor';
import { UserStore } from '../models/user-store';
import { Recipe } from '../models/recipe';
import { normalizeUrl } from '../utils/url-normalizer';
import { RecipeFile } from './file-processor';
import { MetaPost } from './meta/models';

export interface AddRecipeParams {
  link: string;
  extractRecipe: () => Promise<ExtractedRecipe>;
  userId?: string;
}

export interface RecipeWithOwnership extends Recipe {
  inUserList: boolean;
}

export interface GetAllRecipesParams {
  query?: string;
  userId?: string;
}

export interface UpdateRecipeData {
  title?: string;
  ingredients?: string[];
  materials?: string[];
  steps?: string[];
  tags?: string[];
  imageUrl?: string;
  cookingTime?: string;
  servings?: number;
}

export class RecipeService {
  private recipeStore: RecipeStore;
  private userStore: UserStore;
  private recipeExtractor: RecipeExtractor;

  constructor(recipeStore: RecipeStore, userStore: UserStore, recipeExtractor: RecipeExtractor) {
    this.recipeStore = recipeStore;
    this.userStore = userStore;
    this.recipeExtractor = recipeExtractor;
  }

  public async addRecipeFromLink(
    link: string,
    userId: string | undefined
  ): Promise<RecipeWithOwnership> {
    const normalizedLink = normalizeUrl(link);

    return await this.addRecipe({
      link: normalizedLink,
      extractRecipe: async () => await this.getRecipeFromUrl(normalizedLink),
      userId,
    });
  }

  public async addRecipeFromFile(
    recipeFile: RecipeFile,
    userId: string | undefined
  ): Promise<RecipeWithOwnership> {
    return await this.addRecipe({
      link: recipeFile.fileUrl,
      extractRecipe: async () => {
        // Use the prompt generated by FileProcessor
        return await this.recipeExtractor.extractRecipeFromContent(
          recipeFile.fileUrl,
          '', // No separate image URL
          recipeFile.prompt,
          '',
          recipeFile.isImageContent ? '' : recipeFile.fileContent,
          recipeFile.isImageContent ? recipeFile.fileContent : ''
        );
      },
      userId,
    });
  }

  public async addRecipeFromMetaPost(
    metaPost: MetaPost,
    userId: string | undefined
  ): Promise<RecipeWithOwnership> {
    return await this.addRecipe({
      link: metaPost.link,
      extractRecipe: async () => {
        // Use the prompt generated by FileProcessor
        return await this.recipeExtractor.extractRecipeFromContent(
          metaPost.link,
          metaPost.reelUrl,
          metaPost.userContext || '',
          metaPost.systemContext || '',
          metaPost.textContent || '',
          metaPost.imageContent || ''
        );
      },
      userId,
    });
  }

  private async addRecipe(params: AddRecipeParams): Promise<RecipeWithOwnership> {
    const { link, extractRecipe, userId } = params;
    // Check if recipe with this normalized link already exists
    const existingRecipe = await this.recipeStore.getRecipeByNormalizedLink(link);

    if (existingRecipe && existingRecipe.id) {
      // Recipe already exists, add it to the user's collection
      const recipeId = existingRecipe.id;

      if (userId) {
        await this.userStore.addRecipeToUser(userId, recipeId);
      }

      return {
        ...existingRecipe!,
        inUserList: !!userId,
      };
    } else {
      // Recipe doesn't exist, extract details
      try {
        const extractedRecipe = await extractRecipe();

        // Create recipe data
        const recipeData = {
          link,
          title: extractedRecipe.title || 'Untitled Recipe',
          ingredients: extractedRecipe.ingredients || [],
          materials: extractedRecipe.materials || [],
          steps: extractedRecipe.steps || [],
          tags: extractedRecipe.tags || [],
          imageUrl: extractedRecipe.imageUrl || '',
          cookingTime: extractedRecipe.cookingTime || '',
          servings: extractedRecipe.servings || 0,
        };

        // Create new recipe
        const recipeId = await this.recipeStore.createRecipe(recipeData);

        if (userId) {
          // Add the recipe to the user's collection
          await this.userStore.addRecipeToUser(userId, recipeId);
        }

        // Get the complete recipe to return
        const newRecipe = await this.recipeStore.getRecipeById(recipeId);

        return {
          ...newRecipe!,
          inUserList: !!userId,
        };
      } catch (extractError) {
        throw new Error(
          `Failed to extract recipe details: ${extractError instanceof Error ? extractError.message : 'Unknown error'}`
        );
      }
    }
  }

  public async getAllRecipes(params: GetAllRecipesParams): Promise<RecipeWithOwnership[]> {
    const { query, userId } = params;

    // Get all recipes
    const allRecipes = await this.recipeStore.getAllRecipes(query);

    if (userId) {
      // Get the list of recipe IDs this user has access to
      const userRecipeIds = await this.userStore.getUserRecipes(userId);

      // Add inUserList flag to each recipe
      return allRecipes.map(recipe => ({
        ...recipe,
        inUserList: recipe.id ? userRecipeIds.includes(recipe.id) : false,
      }));
    } else {
      return allRecipes.map(recipe => ({
        ...recipe,
        inUserList: false,
      }));
    }
  }

  public async getRecipeById(id: string, userId?: string): Promise<RecipeWithOwnership | null> {
    // Get the recipe
    const recipe = await this.recipeStore.getRecipeById(id);

    if (!recipe) {
      return null;
    }

    // Check if user has this recipe in their list
    const hasRecipe = userId ? await this.userStore.userHasRecipe(userId, id) : false;

    // Return the recipe with an inUserList flag
    return {
      ...recipe,
      inUserList: hasRecipe,
    };
  }

  public async reimportRecipe(id: string): Promise<Recipe> {
    // Get the existing recipe
    const existingRecipe = await this.recipeStore.getRecipeById(id);
    if (!existingRecipe) {
      throw new Error('Recipe not found');
    }

    // Prevent reimporting file-based recipes
    if (existingRecipe.link.startsWith('file://')) {
      throw new Error('Reimporting file-based recipes is not supported');
    } else if (existingRecipe.link.startsWith('meta://')) {
      throw new Error('Reimporting Meta recipes is not supported');
    }

    // Extract recipe details from URL
    const extractedRecipe = await this.recipeExtractor.extractRecipeFromUrl(existingRecipe.link);

    // Update the recipe in the database
    const recipeData = {
      title: extractedRecipe.title || 'Untitled Recipe',
      ingredients: extractedRecipe.ingredients || [],
      materials: extractedRecipe.materials || [],
      steps: extractedRecipe.steps || [],
      tags: extractedRecipe.tags || [],
      imageUrl: extractedRecipe.imageUrl || '',
      cookingTime: extractedRecipe.cookingTime || '',
      servings: extractedRecipe.servings || 0,
    };

    await this.recipeStore.updateRecipe(id, recipeData);

    // Get the updated recipe
    const updatedRecipe = await this.recipeStore.getRecipeById(id);
    if (!updatedRecipe) {
      throw new Error('Failed to retrieve updated recipe');
    }

    return updatedRecipe;
  }

  public async removeRecipeFromUserCollection(userId: string, recipeId: string): Promise<void> {
    // Check if user has access to this recipe
    const hasAccess = await this.userStore.userHasRecipe(userId, recipeId);
    if (!hasAccess) {
      throw new Error('Recipe not found in user collection');
    }

    // Remove recipe from user's collection
    await this.userStore.removeRecipeFromUser(userId, recipeId);
  }

  public async deleteRecipe(id: string): Promise<string> {
    // Check if the recipe exists
    const recipe = await this.recipeStore.getRecipeById(id);
    if (!recipe) {
      throw new Error('Recipe not found');
    }

    // Delete the recipe from the database
    await this.recipeStore.deleteRecipe(id);

    // Also remove the recipe from all users who have it in their collection
    // This prevents orphaned references
    await this.userStore.removeRecipeFromAllUsers(id);

    return id;
  }

  public async getRecipeFromUrl(url: string): Promise<ExtractedRecipe> {
    const normalizedLink = normalizeUrl(url);
    return await this.recipeExtractor.extractRecipeFromUrl(normalizedLink);
  }

  public async refreshRecipe(id: string): Promise<Recipe> {
    // Get existing recipe
    const existingRecipe = await this.recipeStore.getRecipeById(id);
    if (!existingRecipe) {
      throw new Error('Recipe not found');
    }

    // Re-extract recipe details from the link
    const extractedRecipe = await this.recipeExtractor.extractRecipeFromUrl(existingRecipe.link);

    // Update the recipe in the database
    const recipeData = {
      title: extractedRecipe.title || 'Untitled Recipe',
      ingredients: extractedRecipe.ingredients || [],
      materials: extractedRecipe.materials || [],
      steps: extractedRecipe.steps || [],
      tags: extractedRecipe.tags || [],
      imageUrl: extractedRecipe.imageUrl || '',
      cookingTime: extractedRecipe.cookingTime || '',
      servings: extractedRecipe.servings || 0,
    };

    await this.recipeStore.updateRecipe(id, recipeData);

    // Get the updated recipe
    const updatedRecipe = await this.recipeStore.getRecipeById(id);
    if (!updatedRecipe) {
      throw new Error('Failed to retrieve updated recipe');
    }

    return updatedRecipe;
  }
}
