import { RecipeStore } from '../models/recipe-store';
import { ExtractedRecipe, RecipeExtractor } from '../services/recipe-extractor';
import { UserStore } from '../models/user-store';
import { Recipe } from '../models/recipe';
import { normalizeUrl } from '../utils/url-normalizer';
import { RecipeFile } from './file-processor';
import { Logger } from '../utils/logger';

export interface AddRecipeParams {
  link: string;
  extractRecipe: () => Promise<ExtractedRecipe>;
  userId?: string;
}

export interface RecipeWithOwnership extends Recipe {
  inUserList: boolean;
}

export interface GetAllRecipesParams {
  query?: string;
  userId?: string;
  page?: number;
  limit?: number;
  inUserList?: boolean;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface UpdateRecipeData {
  title?: string;
  ingredients?: string[];
  materials?: string[];
  steps?: string[];
  tags?: string[];
  imageUrl?: string;
  cookingTime?: string;
  servings?: number;
}

export class RecipeService {
  private recipeStore: RecipeStore;
  private userStore: UserStore;
  private recipeExtractor: RecipeExtractor;
  private logger: Logger;

  constructor(recipeStore: RecipeStore, userStore: UserStore, recipeExtractor: RecipeExtractor) {
    this.recipeStore = recipeStore;
    this.userStore = userStore;
    this.recipeExtractor = recipeExtractor;
    this.logger = Logger.forContext('RecipeService');
  }

  public async addRecipeFromLink(
    link: string,
    userId: string | undefined
  ): Promise<RecipeWithOwnership> {
    this.logger.info('Adding recipe from link', { link, userId });
    const normalizedLink = normalizeUrl(link);
    this.logger.info('Normalized URL', { originalLink: link, normalizedLink });

    return await this.addRecipe({
      link: normalizedLink,
      extractRecipe: async () => await this.getRecipeFromUrl(normalizedLink),
      userId,
    });
  }

  public async addRecipeFromFile(
    recipeFile: RecipeFile,
    userId: string | undefined
  ): Promise<RecipeWithOwnership> {
    this.logger.info('Adding recipe from file', { fileUrl: recipeFile.fileUrl, userId });

    return await this.addRecipe({
      link: recipeFile.fileUrl,
      extractRecipe: async () => {
        this.logger.info('Extracting recipe from file content', {
          fileUrl: recipeFile.fileUrl,
          isImageContent: recipeFile.isImageContent,
        });

        // Use the prompt generated by FileProcessor
        return await this.recipeExtractor.extractRecipeFromContent(
          recipeFile.fileUrl,
          '', // No separate image URL
          recipeFile.prompt,
          '',
          recipeFile.isImageContent ? '' : recipeFile.fileContent,
          recipeFile.isImageContent ? recipeFile.fileContent : ''
        );
      },
      userId,
    });
  }

  private async addRecipe(params: AddRecipeParams): Promise<RecipeWithOwnership> {
    const { link, extractRecipe, userId } = params;
    this.logger.info('Processing recipe', { link, userId });

    // Check if recipe with this normalized link already exists
    this.logger.info('Checking if recipe already exists', { link });
    const existingRecipe = await this.recipeStore.getRecipeByNormalizedLink(link);

    if (existingRecipe && existingRecipe.id) {
      this.logger.info('Recipe already exists, adding to user collection', {
        recipeId: existingRecipe.id,
        title: existingRecipe.title,
        userId,
      });

      // Recipe already exists, add it to the user's collection
      const recipeId = existingRecipe.id;

      if (userId) {
        await this.userStore.addRecipeToUser(userId, recipeId);
        this.logger.info('Added existing recipe to user collection', { userId, recipeId });
      }

      return {
        ...existingRecipe!,
        inUserList: !!userId,
      };
    } else {
      this.logger.info('Recipe does not exist, extracting details', { link });
      // Recipe doesn't exist, extract details
      try {
        const extractedRecipe = await extractRecipe();
        this.logger.info('Successfully extracted recipe details', {
          title: extractedRecipe.title,
          ingredientsCount: extractedRecipe.ingredients?.length || 0,
          stepsCount: extractedRecipe.steps?.length || 0,
        });

        // Create recipe data
        const recipeData = {
          link,
          title: extractedRecipe.title || 'Untitled Recipe',
          ingredients: extractedRecipe.ingredients || [],
          materials: extractedRecipe.materials || [],
          steps: extractedRecipe.steps || [],
          tags: extractedRecipe.tags || [],
          imageUrl: extractedRecipe.imageUrl || '',
          cookingTime: extractedRecipe.cookingTime || '',
          servings: extractedRecipe.servings || 0,
        };

        this.logger.info('Creating new recipe in database', { title: recipeData.title });
        // Create new recipe
        const recipeId = await this.recipeStore.createRecipe(recipeData);
        this.logger.info('Created new recipe', { recipeId, title: recipeData.title });

        if (userId) {
          // Add the recipe to the user's collection
          this.logger.info('Adding recipe to user collection', { userId, recipeId });
          await this.userStore.addRecipeToUser(userId, recipeId);
        }

        // Get the complete recipe to return
        const newRecipe = await this.recipeStore.getRecipeById(recipeId);

        return {
          ...newRecipe!,
          inUserList: !!userId,
        };
      } catch (extractError) {
        this.logger.error('Failed to extract recipe details', { error: extractError, link });
        throw new Error(
          `Failed to extract recipe details: ${extractError instanceof Error ? extractError.message : 'Unknown error'}`
        );
      }
    }
  }

  public async getAllRecipes(
    params: GetAllRecipesParams
  ): Promise<PaginatedResponse<RecipeWithOwnership>> {
    const { query, userId, page = 1, limit = 20, inUserList } = params;
    this.logger.info('Getting all recipes', { query, userId, page, limit, inUserList });

    const offset = (page - 1) * limit;

    // Use the optimized store method that handles user filtering at the database level
    this.logger.info('Querying database for recipes', { offset, limit });
    const { recipes, total } = await this.recipeStore.getRecipesWithUserFilter({
      searchTerm: query,
      limit,
      offset,
      userId,
      inUserList,
    });
    this.logger.info('Retrieved recipes from database', { count: recipes.length, total });

    // Calculate total pages
    const totalPages = Math.ceil(total / limit);

    // If we have a userId but no inUserList filter was applied at the DB level,
    // we still need to add the inUserList property to each recipe
    let recipesWithOwnership: RecipeWithOwnership[];

    if (userId && inUserList === undefined) {
      this.logger.info('Adding ownership information to recipes', { userId });
      // Get the list of recipe IDs this user has access to
      const userRecipeIds = await this.userStore.getUserRecipes(userId);

      // Add inUserList flag to each recipe
      recipesWithOwnership = recipes.map(recipe => ({
        ...recipe,
        inUserList: recipe.id ? userRecipeIds.includes(recipe.id) : false,
      }));
    } else if (inUserList !== undefined) {
      this.logger.info('Using pre-filtered ownership information', { inUserList });
      // If we used the inUserList filter at the DB level, we already know
      // the value of inUserList for each recipe
      recipesWithOwnership = recipes.map(recipe => ({
        ...recipe,
        inUserList: inUserList,
      }));
    } else {
      this.logger.info('No user ID, marking all recipes as not in user list');
      // No user, so nothing is in any user's list
      recipesWithOwnership = recipes.map(recipe => ({
        ...recipe,
        inUserList: false,
      }));
    }

    // Return paginated response
    return {
      items: recipesWithOwnership,
      total,
      page,
      limit,
      totalPages,
    };
  }

  public async getRecipeById(id: string, userId?: string): Promise<RecipeWithOwnership | null> {
    this.logger.info('Getting recipe by ID', { recipeId: id, userId });

    // Get the recipe
    const recipe = await this.recipeStore.getRecipeById(id);

    if (!recipe) {
      this.logger.info('Recipe not found', { recipeId: id });
      return null;
    }

    // Check if user has this recipe in their list
    let hasRecipe = false;
    if (userId) {
      this.logger.info('Checking if recipe is in user collection', { userId, recipeId: id });
      hasRecipe = await this.userStore.userHasRecipe(userId, id);
      this.logger.info('Recipe in user collection', { inUserList: hasRecipe });
    }

    // Return the recipe with an inUserList flag
    return {
      ...recipe,
      inUserList: hasRecipe,
    };
  }

  public async reimportRecipe(id: string): Promise<Recipe> {
    this.logger.info('Reimporting recipe', { recipeId: id });

    // Get the recipe
    const recipe = await this.recipeStore.getRecipeById(id);

    if (!recipe) {
      this.logger.info('Recipe not found', { recipeId: id });
      throw new Error('Recipe not found');
    }

    // Check if it's a file-based recipe
    if (recipe.link.startsWith('file://')) {
      this.logger.info('Cannot reimport file-based recipe', { recipeId: id, link: recipe.link });
      throw new Error('Reimporting file-based recipes is not supported');
    }

    this.logger.info('Extracting updated recipe data', { recipeId: id, link: recipe.link });
    // Extract recipe details again
    const extractedRecipe = await this.getRecipeFromUrl(recipe.link);

    // Update recipe in database
    const updatedRecipeData = {
      title: extractedRecipe.title || recipe.title,
      ingredients: extractedRecipe.ingredients || recipe.ingredients,
      materials: extractedRecipe.materials || recipe.materials,
      steps: extractedRecipe.steps || recipe.steps,
      tags: extractedRecipe.tags || recipe.tags,
      imageUrl: extractedRecipe.imageUrl || recipe.imageUrl,
      cookingTime: extractedRecipe.cookingTime || recipe.cookingTime,
      servings: extractedRecipe.servings || recipe.servings,
    };

    this.logger.info('Updating recipe in database', {
      recipeId: id,
      title: updatedRecipeData.title,
    });
    await this.recipeStore.updateRecipe(id, updatedRecipeData);

    // Get updated recipe
    const updatedRecipe = await this.recipeStore.getRecipeById(id);

    if (!updatedRecipe) {
      throw new Error('Failed to retrieve updated recipe');
    }

    this.logger.info('Successfully reimported recipe', {
      recipeId: id,
      title: updatedRecipe.title,
    });

    return updatedRecipe;
  }

  public async removeRecipeFromUserCollection(userId: string, recipeId: string): Promise<void> {
    this.logger.info('Removing recipe from user collection', { userId, recipeId });

    // Check if user has the recipe
    const hasRecipe = await this.userStore.userHasRecipe(userId, recipeId);

    if (!hasRecipe) {
      this.logger.info('Recipe not found in user collection', { userId, recipeId });
      throw new Error('Recipe not found in user collection');
    }

    // Remove recipe from user's collection
    await this.userStore.removeRecipeFromUser(userId, recipeId);
    this.logger.info('Successfully removed recipe from user collection', { userId, recipeId });
  }

  public async deleteRecipe(id: string): Promise<string> {
    this.logger.info('Deleting recipe', { recipeId: id });

    // Check if recipe exists
    const recipe = await this.recipeStore.getRecipeById(id);

    if (!recipe) {
      this.logger.info('Recipe not found', { recipeId: id });
      throw new Error('Recipe not found');
    }

    // Delete the recipe from all user collections
    this.logger.info('Removing recipe from all user collections', { recipeId: id });
    await this.userStore.removeRecipeFromAllUsers(id);

    // Delete the recipe itself
    this.logger.info('Deleting recipe from database', { recipeId: id });
    await this.recipeStore.deleteRecipe(id);

    this.logger.info('Successfully deleted recipe', { recipeId: id });
    return id;
  }

  public async getRecipeFromUrl(url: string): Promise<ExtractedRecipe> {
    this.logger.info('Extracting recipe from URL', { url });
    return await this.recipeExtractor.extractRecipeFromUrl(url);
  }

  public async refreshRecipe(id: string): Promise<Recipe> {
    // Get existing recipe
    const existingRecipe = await this.recipeStore.getRecipeById(id);
    if (!existingRecipe) {
      throw new Error('Recipe not found');
    }

    // Re-extract recipe details from the link
    const extractedRecipe = await this.recipeExtractor.extractRecipeFromUrl(existingRecipe.link);

    // Update the recipe in the database
    const recipeData = {
      title: extractedRecipe.title || 'Untitled Recipe',
      ingredients: extractedRecipe.ingredients || [],
      materials: extractedRecipe.materials || [],
      steps: extractedRecipe.steps || [],
      tags: extractedRecipe.tags || [],
      imageUrl: extractedRecipe.imageUrl || '',
      cookingTime: extractedRecipe.cookingTime || '',
      servings: extractedRecipe.servings || 0,
    };

    await this.recipeStore.updateRecipe(id, recipeData);

    // Get the updated recipe
    const updatedRecipe = await this.recipeStore.getRecipeById(id);
    if (!updatedRecipe) {
      throw new Error('Failed to retrieve updated recipe');
    }

    return updatedRecipe;
  }
}
